= locate-conan-package
:toc: preamble

[link=https://github.com/grisumbras/locate-conan-package/actions]
image::https://github.com/grisumbras/locate-conan-package/workflows/ci/badge.svg[Build status]

____
GitHub Action that finds the package folder of a Conan package
____


== Usage

This action is usefull when you want to upload artifacts of your
Conan-generated packages in order to then merge them together and upload to a
Conan server.

Example usage:

[source,yaml]
----
build:
  strategy:
    matrix:
      os: [ubuntu-latest, macOS-latest, windows-latest]

  runs-on: ${{ matrix.os }}

  steps:
    - run: conan create .

    - uses: grisumbras/locate-conan-package@latest
      id: locate_package

    - uses: actions/upload-artifact@v1
      with:
        name: artifacts-${{ matrix.os }}
        path: ${{ steps.locate_package.outputs.path }}
----


== Inputs

=== `name`
Name of the package to locate. If not specified, `name` attribute of the
package recipe is used.

=== `version`
Version  of the package to locate. If not specified, `version` attribute of the
package recipe is used.

=== `user`
User (namespace) of the package to locate. If not specified

. `CONAN_USERNAME` environment variable is used, if present;
. or `default_user` attribute of the package recipe is used, if present;
. or the first part of the value of `GITHUB_REPOSITORY` environment variable
  (before the slash) is used.

=== `channel`
Channel of the package to locate. If not specified

. `CONAN_CHANNEL` environment variable is used, if present;
. or `default_channel` attribute of the package recipe is used, if present;
. or the string `testing`.

=== `reference`
Full reference of the package to locate. If specified all other inputs are
ignored.


== Maintainer
Dmitry Arkhipov <grisumbras@gmail.com>


== Contributing
Patches welcome!


== License
link:LICENSE[BSL-1.0] (C) 2019 Dmitry Arkhipov
